# Generated by Django 4.1 on 2022-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medlyft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('id_number', models.CharField(max_length=13)),
                ('registration_number', models.IntegerField()),
                ('speciality', models.CharField(max_length=225)),
            ],
        ),
    ]
