# Generated by Django 4.1 on 2022-08-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medlyft', '0002_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('id_number', models.CharField(max_length=13)),
                ('folder_number', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
