# Generated by Django 4.1 on 2022-08-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medlyft', '0003_patien'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patien',
            new_name='Patient',
        ),
    ]
