# Generated by Django 4.1 on 2022-08-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medlyft', '0004_rename_patien_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='folder_number',
            new_name='FolderNumber',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='id_number',
            new_name='IDnumber',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
